### ISSUE TITLE
.mp3 背景音乐问题

### ISSUE THREAD

**Issue by weixuelun** [Yish1/Class-Roster-Picker-NEXT#3]
在使用 .mp3 音乐格式的音乐作为背景音乐时，会出现点名器卡死然后直接闪退的情况。

但是只要把格式转换成 .ogg 就不会出现问题。

使用系统：Windows10 19041.264

**Comment by Yish1** [comment]
![image](https://github.com/user-attachments/assets/16b88c06-845b-4ec6-bc3e-7e27b58656cd)
测试mp3正常呀，方便提供报错的mp3文件吗？

**Comment by Yish1** [comment]
另外麻烦查看一下软件目录下的log.txt是否有记录报错信息(此文件每次打开会被重写)
![image](https://github.com/user-attachments/assets/75f092f3-a56f-4c2a-9fe0-77ddf2310887)

**Comment by weixuelun** [comment]
OS：Windows
BUILD：10
PLATFORM：AMD64
TIME：2024-09-15 18:45:27.872583

共读取到 1 个名单
所选文件的路径为: name\默认名单.txt


 ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20']
读取到的有效名单长度: 20
默认名单.txt 的标识符值与记录一致。
加密文件已存在: bak\默认名单.txt.cmxz
云端版本号为: 6.0
当前已经是最新版本
检查更新线程结束
语音播报已禁用
开始点名
播放音乐：D:\沉梦课堂点名器\dmmusic\“Made in Japan” - Ayden George Remix (TNO_ Megacorps Submod OST).mp3
无法播放音乐文件：%s，错误信息：{str(e)}

**Comment by weixuelun** [comment]
报错的 .mp3 文件

https://wwxp.lanzn.com/iyPsW2a1vhsf
密码:5ijv

**Comment by Yish1** [comment]
emmm，发现了一个错误日志的bug  ：“错误信息：{str(e)}”这里应该显示具体报错的...

**Comment by Yish1** [comment]
> 报错的 .mp3 文件
> 
> https://wwxp.lanzn.com/iyPsW2a1vhsf 密码:5ijv

音频未知原因py认为损坏了，所以放不出来闪退，使用格式工厂二次转码后正常

**Comment by Yish1** [comment]
![image](https://github.com/user-attachments/assets/1cddf86d-3672-4169-afb0-1e31bc4da870)
请尝试使用格式工厂二次转码为mp3

**Comment by weixuelun** [comment]
感谢作者的帮助，目前问题已经得到解决。

**Comment by Yish1** [comment]
❤️
